"""add_worker_identity_member_email

Revision ID: 44c6838b209d
Revises: 921336c88fba
Create Date: 2026-06-27 13:55:33.402335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44c6838b209d'
down_revision = '921336c88fba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker_identities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('member_email', sa.String(length=150), nullable=True))
        batch_op.create_index(batch_op.f('ix_worker_identities_member_email'), ['member_email'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker_identities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_worker_identities_member_email'))
        batch_op.drop_column('member_email')

    # ### end Alembic commands ###
