"""add_feedback_columns_to_anomaly_burnout

Revision ID: 6271b49286ae
Revises: 15e22e331f9f
Create Date: 2026-06-24 11:29:04.895192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6271b49286ae'
down_revision = '15e22e331f9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('behavioral_anomalies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feedback', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('feedback_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_behavioral_anomalies_feedback'), ['feedback'], unique=False)

    with op.batch_alter_table('burnout_risks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feedback', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('feedback_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_burnout_risks_feedback'), ['feedback'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('burnout_risks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_burnout_risks_feedback'))
        batch_op.drop_column('feedback_at')
        batch_op.drop_column('feedback')

    with op.batch_alter_table('behavioral_anomalies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_behavioral_anomalies_feedback'))
        batch_op.drop_column('feedback_at')
        batch_op.drop_column('feedback')

    # ### end Alembic commands ###
