"""burnout_risks

Revision ID: 79ae191b2523
Revises: 976595dac5cd
Create Date: 2026-06-20 09:51:03.893841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79ae191b2523'
down_revision = '976595dac5cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
