"""add_scorelog_review_fields

Revision ID: 921336c88fba
Revises: bf6d47e6aa25
Create Date: 2026-06-27 11:23:05.993260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '921336c88fba'
down_revision = 'bf6d47e6aa25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reviewed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('reviewed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('reviewed_by', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score_logs', schema=None) as batch_op:
        batch_op.drop_column('reviewed_by')
        batch_op.drop_column('reviewed_at')
        batch_op.drop_column('reviewed')

    # ### end Alembic commands ###
