"""voice_activity

Revision ID: 976595dac5cd
Revises: b5db1678dd60
Create Date: 2026-06-20 08:32:34.679186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '976595dac5cd'
down_revision = 'b5db1678dd60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voice_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discord_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('guild_id', sa.String(length=50), nullable=False),
    sa.Column('guild_name', sa.String(length=100), nullable=True),
    sa.Column('channel_name', sa.String(length=100), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('hour_of_day', sa.Integer(), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('left_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('voice_activity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_voice_activity_discord_id'), ['discord_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voice_activity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_voice_activity_discord_id'))

    op.drop_table('voice_activity')
    # ### end Alembic commands ###
