"""automod_triggers_and_alert_channel

Revision ID: 9bca449cd417
Revises: d0dc5c46e03b
Create Date: 2026-06-21 11:17:09.113340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bca449cd417'
down_revision = 'd0dc5c46e03b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automod_triggers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.String(length=50), nullable=False),
    sa.Column('rule_id', sa.String(length=50), nullable=True),
    sa.Column('rule_name', sa.String(length=200), nullable=True),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('user_name', sa.String(length=100), nullable=True),
    sa.Column('channel_id', sa.String(length=50), nullable=True),
    sa.Column('channel_name', sa.String(length=100), nullable=True),
    sa.Column('content_snippet', sa.Text(), nullable=True),
    sa.Column('action_taken', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('automod_triggers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_automod_triggers_guild_id'), ['guild_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_automod_triggers_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('automod_rules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alert_channel_id', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('automod_rules', schema=None) as batch_op:
        batch_op.drop_column('alert_channel_id')

    with op.batch_alter_table('automod_triggers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_automod_triggers_user_id'))
        batch_op.drop_index(batch_op.f('ix_automod_triggers_guild_id'))

    op.drop_table('automod_triggers')
    # ### end Alembic commands ###
