"""ping_join_events

Revision ID: b5db1678dd60
Revises: fb59596f4c64
Create Date: 2026-06-19 21:06:13.569870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5db1678dd60'
down_revision = 'fb59596f4c64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ping_join_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.String(length=50), nullable=False),
    sa.Column('guild_name', sa.String(length=100), nullable=True),
    sa.Column('moderator_id', sa.String(length=50), nullable=False),
    sa.Column('moderator_name', sa.String(length=100), nullable=True),
    sa.Column('channel', sa.String(length=100), nullable=True),
    sa.Column('new_members', sa.Integer(), nullable=True),
    sa.Column('joiners', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ping_join_events')
    # ### end Alembic commands ###
