"""add_behavior_baselines

Revision ID: bf6d47e6aa25
Revises: add_hour_error_history
Create Date: 2026-06-27 08:47:43.383029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf6d47e6aa25'
down_revision = 'add_hour_error_history'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guild_activity_baselines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.String(length=50), nullable=False),
    sa.Column('hourly_mean', sa.JSON(), nullable=True),
    sa.Column('hourly_std', sa.JSON(), nullable=True),
    sa.Column('peak_hours', sa.JSON(), nullable=True),
    sa.Column('total_msgs_seen', sa.Integer(), nullable=True),
    sa.Column('days_of_history', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('guild_activity_baselines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guild_activity_baselines_guild_id'), ['guild_id'], unique=True)

    op.create_table('user_behavior_baselines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discord_id', sa.String(length=50), nullable=False),
    sa.Column('guild_id', sa.String(length=50), nullable=True),
    sa.Column('hourly_profile_90d', sa.JSON(), nullable=True),
    sa.Column('mean_daily_msgs_90d', sa.Float(), nullable=True),
    sa.Column('std_daily_msgs_90d', sa.Float(), nullable=True),
    sa.Column('mean_msg_length_90d', sa.Float(), nullable=True),
    sa.Column('off_hours_ratio_90d', sa.Float(), nullable=True),
    sa.Column('mean_daily_msgs_7d', sa.Float(), nullable=True),
    sa.Column('off_hours_ratio_7d', sa.Float(), nullable=True),
    sa.Column('volume_drift', sa.Float(), nullable=True),
    sa.Column('pattern_drift', sa.Float(), nullable=True),
    sa.Column('is_drifting', sa.Boolean(), nullable=True),
    sa.Column('recent_anomaly_count', sa.Integer(), nullable=True),
    sa.Column('recent_burnout_score', sa.Float(), nullable=True),
    sa.Column('forecast_error_mean', sa.Float(), nullable=True),
    sa.Column('total_msgs_seen', sa.Integer(), nullable=True),
    sa.Column('baseline_confidence', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('discord_id', 'guild_id', name='uq_user_baseline_guild')
    )
    with op.batch_alter_table('user_behavior_baselines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_behavior_baselines_discord_id'), ['discord_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_behavior_baselines_guild_id'), ['guild_id'], unique=False)

    with op.batch_alter_table('score_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_score_logs_task_id'))
        batch_op.drop_column('priority_multiplier')
        batch_op.drop_column('task_id')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('is_late')
        batch_op.drop_column('is_early')
        batch_op.drop_column('priority_at_completion')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority_at_completion', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_early', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_late', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))

    with op.batch_alter_table('score_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('priority_multiplier', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('1.0'), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('ix_score_logs_task_id'), ['task_id'], unique=False)

    with op.batch_alter_table('user_behavior_baselines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_behavior_baselines_guild_id'))
        batch_op.drop_index(batch_op.f('ix_user_behavior_baselines_discord_id'))

    op.drop_table('user_behavior_baselines')
    with op.batch_alter_table('guild_activity_baselines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guild_activity_baselines_guild_id'))

    op.drop_table('guild_activity_baselines')
    # ### end Alembic commands ###
