"""add PendingBan and PendingTimeout tables

Revision ID: c84ae5824645
Revises: 9bca449cd417
Create Date: 2026-06-22 07:01:18.454090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c84ae5824645'
down_revision = '9bca449cd417'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_bans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('banner_id', sa.String(length=50), nullable=False),
    sa.Column('banner_name', sa.String(length=100), nullable=False),
    sa.Column('user_name', sa.String(length=100), nullable=False),
    sa.Column('reason', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pending_bans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pending_bans_guild_id'), ['guild_id'], unique=False)

    op.create_table('pending_timeouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('mod_id', sa.String(length=50), nullable=False),
    sa.Column('mod_name', sa.String(length=100), nullable=False),
    sa.Column('until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pending_timeouts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pending_timeouts_guild_id'), ['guild_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_timeouts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pending_timeouts_guild_id'))

    op.drop_table('pending_timeouts')
    with op.batch_alter_table('pending_bans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pending_bans_guild_id'))

    op.drop_table('pending_bans')
    # ### end Alembic commands ###
