"""add_guild_member_presence_fields

Revision ID: cb7873b8d628
Revises: a1b2c3d4e5f6
Create Date: 2026-06-21 10:08:39.230839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb7873b8d628'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guild_info', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guild_info_guild_id'))
        batch_op.create_index(batch_op.f('ix_guild_info_guild_id'), ['guild_id'], unique=True)

    with op.batch_alter_table('guild_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_online', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('last_seen_online', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_message_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('activity_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('activity_type', sa.String(length=20), nullable=True))

    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workers_discord_id'))
        batch_op.create_index(batch_op.f('ix_workers_discord_id'), ['discord_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workers_discord_id'))
        batch_op.create_index(batch_op.f('ix_workers_discord_id'), ['discord_id'], unique=False)

    with op.batch_alter_table('guild_members', schema=None) as batch_op:
        batch_op.drop_column('activity_type')
        batch_op.drop_column('activity_name')
        batch_op.drop_column('status')
        batch_op.drop_column('last_message_at')
        batch_op.drop_column('last_seen_online')
        batch_op.drop_column('is_online')

    with op.batch_alter_table('guild_info', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guild_info_guild_id'))
        batch_op.create_index(batch_op.f('ix_guild_info_guild_id'), ['guild_id'], unique=False)

    # ### end Alembic commands ###
