"""add_guild_id_to_score_log

Revision ID: d0dc5c46e03b
Revises: cb7873b8d628
Create Date: 2026-06-21 10:28:18.952324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0dc5c46e03b'
down_revision = 'cb7873b8d628'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guild_id', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_score_logs_guild_id'), ['guild_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_score_logs_guild_id'))
        batch_op.drop_column('guild_id')

    # ### end Alembic commands ###
