"""add organisation, orgmember, workeridentity, source column

Revision ID: d61480bb4e91
Revises: eb8f4d2a1c0d
Create Date: 2026-06-24 08:32:23.718829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd61480bb4e91'
down_revision = 'eb8f4d2a1c0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organisations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('email_domain', sa.String(length=150), nullable=True),
    sa.Column('api_key', sa.String(length=128), nullable=False),
    sa.Column('plan', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('share_feature_vectors', sa.Boolean(), nullable=True),
    sa.Column('share_anomaly_types', sa.Boolean(), nullable=True),
    sa.Column('store_task_content', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organisations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organisations_api_key'), ['api_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_organisations_slug'), ['slug'], unique=True)

    op.create_table('org_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'email', name='uq_org_member_email')
    )
    with op.batch_alter_table('org_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_org_members_org_id'), ['org_id'], unique=False)

    op.create_table('worker_identities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('discord_id', sa.String(length=50), nullable=True),
    sa.Column('org_employee_id', sa.String(length=100), nullable=True),
    sa.Column('jira_account_id', sa.String(length=100), nullable=True),
    sa.Column('display_name', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('linked_at', sa.DateTime(), nullable=True),
    sa.Column('linked_by', sa.String(length=150), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('consent_community_prior', sa.Boolean(), nullable=True),
    sa.Column('consent_federated', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'discord_id', name='uq_identity_org_discord'),
    sa.UniqueConstraint('org_id', 'org_employee_id', name='uq_identity_org_employee')
    )
    with op.batch_alter_table('worker_identities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_worker_identities_discord_id'), ['discord_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_worker_identities_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_worker_identities_worker_id'), ['worker_id'], unique=False)

    with op.batch_alter_table('behavioral_anomalies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=30), nullable=True))
        batch_op.create_index(batch_op.f('ix_behavioral_anomalies_source'), ['source'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('behavioral_anomalies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_behavioral_anomalies_source'))
        batch_op.drop_column('source')

    with op.batch_alter_table('worker_identities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_worker_identities_worker_id'))
        batch_op.drop_index(batch_op.f('ix_worker_identities_org_id'))
        batch_op.drop_index(batch_op.f('ix_worker_identities_discord_id'))

    op.drop_table('worker_identities')
    with op.batch_alter_table('org_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_org_members_org_id'))

    op.drop_table('org_members')
    with op.batch_alter_table('organisations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organisations_slug'))
        batch_op.drop_index(batch_op.f('ix_organisations_api_key'))

    op.drop_table('organisations')
    # ### end Alembic commands ###
