"""Work Engine: external_id, source, external_url, priority

Revision ID: eb8f4d2a1c0d
Revises: 19eedc79b37
Create Date: 2026-06-22 13:59:19.979792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb8f4d2a1c0d'
down_revision = '19eedc79b37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('external_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('external_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('priority', sa.String(length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_tasks_external_id'), ['external_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_external_id'))
        batch_op.drop_column('priority')
        batch_op.drop_column('external_url')
        batch_op.drop_column('external_id')
        batch_op.drop_column('source')

    # ### end Alembic commands ###
