"""automod_rules

Revision ID: fb59596f4c64
Revises: 85b9c14510e2
Create Date: 2026-06-19 19:51:46.961650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb59596f4c64'
down_revision = '85b9c14510e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automod_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.String(length=50), nullable=False),
    sa.Column('rule_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('creator_id', sa.String(length=50), nullable=True),
    sa.Column('creator_name', sa.String(length=100), nullable=True),
    sa.Column('trigger_type', sa.String(length=50), nullable=False),
    sa.Column('trigger_text', sa.Text(), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('exempt_roles', sa.Text(), nullable=True),
    sa.Column('exempt_channels', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('behavioral_anomalies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discord_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('guild_id', sa.String(length=50), nullable=True),
    sa.Column('anomaly_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.Float(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=True),
    sa.Column('cleared_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('behavioral_anomalies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_behavioral_anomalies_discord_id'), ['discord_id'], unique=False)

    op.create_table('community_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discord_id', sa.String(length=50), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('score_impact', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guild_channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.String(length=50), nullable=False),
    sa.Column('channel_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('topic', sa.Text(), nullable=True),
    sa.Column('channel_type', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guild_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('owner_id', sa.String(length=50), nullable=True),
    sa.Column('owner_name', sa.String(length=100), nullable=True),
    sa.Column('member_count', sa.Integer(), nullable=True),
    sa.Column('online_count', sa.Integer(), nullable=True),
    sa.Column('staff_count', sa.Integer(), nullable=True),
    sa.Column('bot_count', sa.Integer(), nullable=True),
    sa.Column('role_count', sa.Integer(), nullable=True),
    sa.Column('prefix', sa.Text(), nullable=True),
    sa.Column('store_content', sa.Boolean(), nullable=True),
    sa.Column('scanned_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id')
    )
    op.create_table('guild_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.String(length=50), nullable=False),
    sa.Column('member_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('is_bot', sa.Boolean(), nullable=True),
    sa.Column('is_owner', sa.Boolean(), nullable=True),
    sa.Column('is_staff', sa.Boolean(), nullable=True),
    sa.Column('is_manually_set', sa.Boolean(), nullable=True),
    sa.Column('role_ids', sa.Text(), nullable=True),
    sa.Column('top_role_position', sa.Integer(), nullable=True),
    sa.Column('total_messages', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guild_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.String(length=50), nullable=False),
    sa.Column('role_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('can_ban', sa.Boolean(), nullable=True),
    sa.Column('can_kick', sa.Boolean(), nullable=True),
    sa.Column('can_manage_messages', sa.Boolean(), nullable=True),
    sa.Column('can_manage_guild', sa.Boolean(), nullable=True),
    sa.Column('can_manage_roles', sa.Boolean(), nullable=True),
    sa.Column('is_mod', sa.Boolean(), nullable=True),
    sa.Column('is_manually_set', sa.Boolean(), nullable=True),
    sa.Column('member_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mention_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mentioner_id', sa.String(length=50), nullable=False),
    sa.Column('mentioner_name', sa.String(length=100), nullable=True),
    sa.Column('mentioned_id', sa.String(length=50), nullable=False),
    sa.Column('mentioned_name', sa.String(length=100), nullable=True),
    sa.Column('guild_id', sa.String(length=50), nullable=False),
    sa.Column('channel_name', sa.String(length=100), nullable=True),
    sa.Column('reply_time_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discord_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('guild_id', sa.String(length=50), nullable=False),
    sa.Column('channel_name', sa.String(length=100), nullable=True),
    sa.Column('is_public_channel', sa.Boolean(), nullable=True),
    sa.Column('message_length', sa.Integer(), nullable=True),
    sa.Column('message_content', sa.Text(), nullable=True),
    sa.Column('hour_of_day', sa.Integer(), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('discord_id', sa.String(length=50), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('discord_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('admin_corrections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('original_score_change', sa.Float(), nullable=False),
    sa.Column('corrected_score_change', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('corrected_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('score_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('change', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(length=300), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('admin_correction', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('points_awarded', sa.Float(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('extra_contribution', sa.Boolean(), nullable=True),
    sa.Column('extra_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    op.drop_table('score_logs')
    op.drop_table('admin_corrections')
    op.drop_table('workers')
    op.drop_table('message_records')
    op.drop_table('mention_records')
    op.drop_table('guild_roles')
    op.drop_table('guild_members')
    op.drop_table('guild_info')
    op.drop_table('guild_channels')
    op.drop_table('community_events')
    with op.batch_alter_table('behavioral_anomalies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_behavioral_anomalies_discord_id'))

    op.drop_table('behavioral_anomalies')
    op.drop_table('automod_rules')
    # ### end Alembic commands ###
